<div class="container ministry-detail">
	<section class="header">
		<h1>Ministry of <?php echo $ministry['ministry_name'] ?></h1>
	</section><br>
	<section class="content">
		<div class="row">
			<section class="col-lg-3 side-bar">
				<div class="list-group">
					<a href="/ministry/detail/profile/<?php echo $ministry['ministry_id'] ?>" 
						class="list-group-item <?php echo ($section == 'profile') ? 'active' : ''; ?>">Profile</a>
					<a href="/ministry/detail/members/<?php echo $ministry['ministry_id'] ?>" 
						class="list-group-item <?php echo ($section == 'members') ? 'active' : ''; ?>">Members</a>
					<a href="/ministry/detail/events/<?php echo $ministry['ministry_id'] ?>" 
						class="list-group-item <?php echo ($section == 'events') ? 'active' : ''; ?>">Events</a>
				</div>
			</section>
			<section class="col-lg-9 main">
				<?php if ($section == 'profile'): ?>
					<?php include('_profile.phtml'); ?>
				<?php elseif ($section == 'members'): ?>
					<?php include('_members.phtml'); ?>
				<?php elseif ($section == 'events'): ?>
					<?php include('_events.phtml'); ?>
				<?php endif; ?>
			</section>
		</div>
	</section>
</div>

<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Modal title</h4>
			</div>
			<div class="modal-body">
				<form action="/ministry/member/action/update/<?php echo $ministry['ministry_id'] ?>" 
					method="post" class="form-horizontal" role="form" id="form-edit-member">
					
					<div class="message"></div>
					<input type="hidden" name="id" class="member_id">
					<div class="form-group">
						<label for="inputName" class="col-lg-2 control-label">Name</label>
						<div class="col-lg-4">
							<input type="text" name="first_name" 
							class="form-control" id="inputName" placeholder="First Name">
						</div>
						<div class="col-lg-4">
							<input type="text" name="last_name" 
							class="form-control" placeholder="Last Name">
						</div>
					</div>
					<div class="form-group">
						<label for="inputEmail" class="col-lg-2 control-label">Email</label>
						<div class="col-lg-8">
							<input type="text" name="email" 
							class="form-control" id="inputEmail" placeholder="Email">
						</div>
					</div>
					<div class="form-group">
						<label for="inputAddress" class="col-lg-2 control-label">Address</label>
						<div class="col-lg-8">
							<input type="text" name="address" 
							class="form-control" id="inputAddress" placeholder="Address">
						</div>
					</div>
					<div class="form-group">
						<label for="inputPhone" class="col-lg-2 control-label">Phone</label>
						<div class="col-lg-8">
							<input type="text" name="phone" 
							class="form-control" id="inputPhone" placeholder="Phone">
						</div>
					</div>
					<div class="form-group">
						<label for="inputAge" class="col-lg-2 control-label">Age</label>
						<div class="col-lg-2">
							<input type="text" name="age" 
							class="form-control" id="inputAge" placeholder="Age">
						</div>
					</div>
					<div class="form-group">
						<div class="col-lg-offset-2 col-lg-10">
							<input type="submit" class="btn btn-success" name="create_member" value="Submit">
					    </div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary">Save changes</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
	$(document).ready(function(){
		$('a.edit-member').click(function(){
			var $this 	= $(this),
				id 		= $this.attr('data-id');

			$.ajax({
				type: 'get',
				url: '/ministry/member/action/detail',
				dataType: 'json',
				data: { getMember : 'update', id : id },
				success: function(response){
					console.log(response);

					var firstName = response.member_first,
						lastName = response.member_last,
						email = response.member_email,
						address = response.member_address,
						phone = response.member_phone,
						age = response.member_age;

					$('form#form-edit-member input.member_id').val(id);
					$('form#form-edit-member input[name="first_name"]').val(firstName);
					$('form#form-edit-member input[name="last_name"]').val(lastName);
					$('form#form-edit-member input[name="email"]').val(email);
					$('form#form-edit-member input[name="address"]').val(address);
					$('form#form-edit-member input[name="phone"]').val(phone);
					$('form#form-edit-member input[name="age"]').val(age);
				}
			});
		});

		$('form#form-edit-member').submit(function(){
			var $this 		= $(this),
				firstname 	= $this.find('input[name="first_name"]').val(),
				lastname 	= $this.find('input[name="last_name"]').val(),
				email 		= $this.find('input[name="email"]').val(),
				address 	= $this.find('input[name="address"]').val(),
				phone 		= $this.find('input[name="phone"]').val(),
				age 		= $this.find('input[name="age"]').val();

			var inputs = [firstname, lastname, email, address, phone, age];
			for (var i = 0; i < inputs.length; i++) {
				if (inputs[i].length == 0) {
					error = '<div class="alert alert-danger">All fields are required!</div>';
					$this.find('div.message').html(error);

					return false;
				};

				if (i == 4 && !$.isNumeric(inputs[i])) {
					error = '<div class="alert alert-danger">Invalid data for phone! must be integer.</div>';
					$this.find('div.message').html(error);

					return false;	
				};

				if (i == 5 && !$.isNumeric(inputs[i])) {
					error = '<div class="alert alert-danger">Invalid data for age! must be integer.</div>';
					$this.find('div.message').html(error);

					return false;	
				};
			};

			return true;
		});

		$('a.delete-member').click(function(){
			if (!confirm('Are you sure?')) {
				return false;
			};

			return true;
		});	
	});
</script>