<div class="container update">
	<section class="header">
		<h2 class="pull-left"><?php echo $ministry['ministry_name'] ?> <small>Update Ministry</small></h2>
		<a href="/ministry/list" class="btn btn-success pull-right back">Back to list</a>
		<hr class="clear">
	</section>
	<section class="main">
		<form action="/ministry/update" method="post"> 
			<fieldset>
				<div class="input-hidden">
					<input type="hidden" name="id" value="<?php echo $ministry['ministry_id']; ?>">
				</div>
				<div class="form-group">
					<label for="inputName">Name</label>
					<input type="text" class="form-control" name="name" id="inputName" value="<?php echo $ministry['ministry_name']; ?>">
				</div>
				<div class="form-group">
					<label for="inputDescription">Description</label>
					<textarea name="description" class="form-control" name="description" id="inputDescription" rows="10"><?php echo $ministry['ministry_excerpt']; ?></textarea>
				</div>
				<input type="submit" class="btn btn-primary pull-right" name="update" value="Submit">
			</fieldset>
		</form>
	</section>
</div>