<style type="text/css">
	
</style>
<div class="container ministry-detail">
	<section class="header">
		<h1>Ministry Name</h1>
	</section><br>
	<section class="content">
		<div class="row">
			<section class="col-lg-3 side-bar">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#">Members</a></li>
					<li><a href="#">Profile</a></li>
					<li><a href="#">Messages</a></li>
				</ul>
			</section>
			<section class="col-lg-9 main"></section>
		</div>
	</section>
</div>