<style type="text/css">
	.list section.header hr { clear: both; }
	.list section.header a { margin-top: 20px; }
</style>
<div class="container list">
	<section class="header">
		<h2 class="pull-left">Parish Ministry <small>admin</small></h2>
		<a href="/ministry/create" class="btn btn-success pull-right"><i class="icon-plus-sign"></i> Create Ministry</a>
		<hr>
	</section>
	<section class="main">
		<div class="row">
			<?php foreach($ministries as $ministry): ?>
				<div class="col-lg-3">
					<div class="thumbnail">
						<a href="/ministry/detail/<?php echo $ministry['ministry_id']; ?>"><img data-src="holder.js/100%x180"></a>
						<div class="caption">
							<h3><a href="/ministry/detail/<?php echo $ministry['ministry_id']; ?>"><?php echo $ministry['ministry_name']; ?></a></h3>
							<p>
								<?php 
									$description = $ministry['ministry_excerpt'];
									$description = strlen($description) > 100 ? substr($description, 0, 100).'...': $description; 
									echo $description;
								?>
							</p>
						</div>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
	</section>
</div>