<div class="banner-wrapper">
	<section class="banner">
		<div class="banner-signup">
			<img src="/assets/img/folder.png">
			<div class="reg-ministry">
				<h3>Register to one<br> of our Ministries</h3>
				<a href="#">Signup Now</a>
			</div>
		</div>
		<div class="youth-ministry">
			<h2>Youth Ministry</h2>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
			</p>
			<a href="#">Read More</a>
		</div>
	</section>
</div>
<section class="content-wrapper">
	<section class="home content">
		<section class="main clearfix">
			<div class="excerpt">
				<div class="excerpt-temp">
					<img src="/assets/img/cam.png">
					<h4>What We Do</h4>
					<p>Lorem ipsum Nisi est ea ut quis consequat velit Duis dolore in proident 
						incididunt sed dolor sit Ut consequat magna sunt ad Excepteur.</p>
				</div>
			</div>
			<div class="where">
				<div class="where-temp">
					<img src="/assets/img/map.png">
					<h4>Where We At</h4>
					<p>Lorem ipsum Nisi est ea ut quis consequat velit Duis dolore in proident 
						incididunt sed dolor sit Ut consequat magna sunt ad Excepteur.</p>
				</div>
			</div>
		</section>
		<section class="sidebar">
			<div class="updates">
				<h3>Events and Updates</h3>
				<ul>
					<li>
						<h5><a href="#">Youth Encounter <small>come and see</small></a></h5>
						<p>Lorem ipsum Ut amet irure id in tempor quis qui exercitation minim 
							laborum in exercitation dolor Ut pariatur irure veniam</p>
						<a href="#" class="view">see more..</a>
					</li>
					<li>
						<h5><a href="#">Summer Youth Camp</a></h5>
						<p>Lorem ipsum Ut amet irure id in tempor quis qui exercitation minim 
							laborum in exercitation dolor Ut pariatur irure veniam</p>
						<a href="#" class="view">see more..</a>
					</li>
					<li>
						<h5><a href="#">October Fun Run</a></h5>
						<p>Lorem ipsum Ut amet irure id in tempor quis qui exercitation minim 
							laborum in exercitation dolor Ut pariatur irure veniam</p>
						<a href="#" class="view">see more..</a>
					</li>
				</ul>
			</div>
		</section>
	<div class="fb-comments" data-href="http://galleon.ph/" data-width="960"></div>
	</section>
</section>