<section class="banner">
	<div class="banner-signup">
		<img src="/assets/img/folder.png">
		<div class="reg-ministry">
			<h3>Register to one<br> of our Ministries</h3>
			<a href="#">Signup Now</a>
		</div>
	</div>
	<div class="youth-ministry">
		<h2>Youth Ministry</h2>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
		</p>
		<a href="#">Read More</a>
	</div>
</section>
<section class="content">
	<section class="main">
		
	</section>
	<section class="sidebar">
		
	</section>
</section>